<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Confirm password' => 'Bevestigen',
    'Create' => 'Aanmaken',
    'Create new user.' => 'Nieuwe gebruiker',
    'Email' => 'E-mail',
    'No such user.' => 'Gebruiker bestaat niet',
    'Password' => 'Wachtwoord',
    'Password reset request' => 'Wachtwoord resetten',
    'Passwords do not match.' => 'Wachtwoorden komen niet overeen.',
    'Passwords don\'t match.' => 'Wachtwoorden komen niet overeen.',
    'Reset password for account with email address "{email}".' => 'Wachtwoord resetten voor account met e-mailadres "{email}".',
    'Roles' => 'Rollen',
    'The user details have been updated.' => 'De gebruikersgegevens zijn bijgewerkt.',
    'Unable to update password. Please try again or contact support..' => 'Het is niet mogelijk het wachtwoord bij te werken. Neem contact op met een beheerder.',
    'Update' => 'Bijwerken.',
    'Update password' => 'Wachtwoord bijwerken.',
    'Update user.' => 'Gebruiker bijwerken.',
    'Users' => 'Gebruikers',
    'Your password has been updated successfully. You can safely close this window.' => 'Het wachtwoord is bijgewerkt. Dit venster kan nu gesloten worden.',
];
